// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {app} from '../models';

export function DeleteConnection(arg1:string):Promise<Array<storage.ConnectionMetadata>>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetConnections():Promise<Array<storage.ConnectionMetadata>>;

export function GetProviderModels(arg1:string,arg2:string):Promise<Array<string>>;

export function LoadModel(arg1:string):Promise<storage.ConnectionMetadata>;

export function SaveConnection(arg1:storage.ConnectionMetadata,arg2:string):Promise<Array<storage.ConnectionMetadata>>;

export function SelectGGUFFolder():Promise<Array<app.GGUFFile>>;

export function SendMessage(arg1:string):Promise<string>;

export function TestConnection(arg1:storage.ConnectionMetadata,arg2:string):Promise<string>;
