// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetProviderModels(arg1, arg2) {
  return window['go']['app']['App']['GetProviderModels'](arg1, arg2);
}

export function LoadModel(arg1) {
  return window['go']['app']['App']['LoadModel'](arg1);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['app']['App']['SaveConnection'](arg1, arg2);
}

export function SelectGGUFFolder() {
  return window['go']['app']['App']['SelectGGUFFolder']();
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2);
}
