// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {app} from '../models';
import {attacks} from '../models';

export function DeleteConnection(arg1:string):Promise<Array<storage.ConnectionMetadata>>;

export function EvaluatePrompt(arg1:string):Promise<string>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetAttackCategories():Promise<Array<attacks.AttackCategory>>;

export function GetConnections():Promise<Array<storage.ConnectionMetadata>>;

export function GetPromptsForScan(arg1:Array<string>,arg2:number):Promise<Array<string>>;

export function GetProviderModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetSidecarStatus():Promise<string>;

export function LoadModel(arg1:string):Promise<storage.ConnectionMetadata>;

export function RenameConnection(arg1:string,arg2:string):Promise<Array<storage.ConnectionMetadata>>;

export function SaveConnection(arg1:storage.ConnectionMetadata,arg2:string):Promise<Array<storage.ConnectionMetadata>>;

export function SelectGGUFFile():Promise<string>;

export function SendMessage(arg1:string):Promise<string>;

export function TestConnection(arg1:storage.ConnectionMetadata,arg2:string):Promise<string>;

export function UnloadModel(arg1:string):Promise<void>;
