// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScanRecord(arg1) {
  return window['go']['app']['App']['CreateScanRecord'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['app']['App']['DeleteConnection'](arg1);
}

export function EvaluateCompliance(arg1, arg2) {
  return window['go']['app']['App']['EvaluateCompliance'](arg1, arg2);
}

export function FinalizeScan(arg1, arg2) {
  return window['go']['app']['App']['FinalizeScan'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetAttackCategories() {
  return window['go']['app']['App']['GetAttackCategories']();
}

export function GetConnections() {
  return window['go']['app']['App']['GetConnections']();
}

export function GetPromptsForScan(arg1, arg2) {
  return window['go']['app']['App']['GetPromptsForScan'](arg1, arg2);
}

export function GetProviderModels(arg1, arg2) {
  return window['go']['app']['App']['GetProviderModels'](arg1, arg2);
}

export function GetSidecarStatus() {
  return window['go']['app']['App']['GetSidecarStatus']();
}

export function LoadModel(arg1) {
  return window['go']['app']['App']['LoadModel'](arg1);
}

export function RenameConnection(arg1, arg2) {
  return window['go']['app']['App']['RenameConnection'](arg1, arg2);
}

export function SaveConnection(arg1, arg2) {
  return window['go']['app']['App']['SaveConnection'](arg1, arg2);
}

export function SaveScanResult(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveScanResult'](arg1, arg2, arg3, arg4);
}

export function SelectGGUFFolder() {
  return window['go']['app']['App']['SelectGGUFFolder']();
}

export function SendMessage(arg1) {
  return window['go']['app']['App']['SendMessage'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2);
}

export function UnloadModel(arg1) {
  return window['go']['app']['App']['UnloadModel'](arg1);
}
